import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Button} from 'antd'
import Markdown from './components/Markdown/Markdown'
import ReactMarkdown from 'react-markdown'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Markdown></Markdown>
      <Button>test</Button>
      <ReactMarkdown># Hello, *world*!</ReactMarkdown>
    </div>
  )
}
